### ISSUE TITLE
最后会报错

### ISSUE THREAD

**Issue by tucoheisenberg** [Initsnow/bilibili-comment-cleaning#2]
最后会报错，这个样子
thread 'tokio-runtime-worker' panicked at src/main.rs:481:21:
Undefined URI:https://app.biligame.com/page/transfer_reply.html?id=101772&no=CM1423077612212850688&sourcefrom=100006&hotComment=true
Can't get oid
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Initsnow** [comment]
> 最后会报错，这个样子 thread 'tokio-runtime-worker' panicked at src/main.rs:481:21: Undefined URI:https://app.biligame.com/page/transfer_reply.html?id=101772&no=CM1423077612212850688&sourcefrom=100006&hotComment=true Can't get oid note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

删除评价需要其他验证，我不会js逆向，直接跳过处理了
https://github.com/Initsnow/bilibili-comment-cleaning/releases/tag/v0.4.22

**Comment by tucoheisenberg** [comment]
谢谢哥，解决啦！
