### ISSUE TITLE
報錯

### ISSUE THREAD

**Issue by jason21415** [Initsnow/bilibili-comment-cleaning#5]
![錯誤](https://github.com/user-attachments/assets/bd9db3fe-4667-4d8e-b105-550a68187f06)
[LOG.txt](https://github.com/user-attachments/files/17812115/LOG.txt)

**Comment by Initsnow** [comment]
重试下还是一样的报错吗

**Comment by jason21415** [comment]
重登可以了 似乎是Cookie的問題

**Comment by Initsnow** [comment]
看报错是http库的问题，应该是少数情况吧
