### ISSUE TITLE
触发aicu的cf防火墙，可否考虑自行获取导入？

### ISSUE THREAD

**Issue by CuervoCarlos** [Initsnow/bilibili-comment-cleaning#6]
`thread 'tokio-runtime-worker' panicked at \bilibili-comment-cleaning\bilibili-comment-cleaning\src\lib.rs:21:29:
Cannot get json, res string: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1">
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by Initsnow** [comment]
https://github.com/iced-rs/iced/issues/1002

**Comment by Initsnow** [comment]
https://www.github.com/iced-rs/iced/issues/1002
> 服了，不加www.直接复制粘贴会自动在原issue创建个mention
